generatorName: rust
outputDir: samples/client/petstore/rust/reqwest/petstore-google-cloud-auth
library: reqwest
inputSpec: modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/rust
additionalProperties:
  supportAsync: false
  supportGoogleCloudAuth: true
  packageName: petstore-reqwest-google-cloud-auth
